/**
 * Native Memory Bridge
 *
 * Syncs autoclaude's structured data (decisions, learnings with decay scores)
 * to Claude Code's native memory directory so both systems complement each other.
 *
 * Claude Code's native memory lives at:
 *   ~/.claude/projects/<project-key>/memory/
 *
 * Where <project-key> is the absolute project path with '/' replaced by '-'.
 *
 * We write:
 *   - decisions.md — active decisions with categories
 *   - learnings.md — top learnings with relevance scores
 *   - MEMORY.md   — concise index (append/update our section)
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { getActiveDecisions, getTopLearnings } from './memory';
import { logger } from '../util/logger';

// ---------------------------------------------------------------------------
// Path resolution
// ---------------------------------------------------------------------------

/**
 * Converts an absolute project path to the Claude Code native memory directory.
 * e.g. /home/blaine/projects/autoclaude → ~/.claude/projects/-home-blaine-projects-autoclaude/memory/
 */
export function getNativeMemoryDir(projectPath: string): string {
  const key = projectPath.replace(/\//g, '-');
  return path.join(os.homedir(), '.claude', 'projects', key, 'memory');
}

// ---------------------------------------------------------------------------
// Sync functions
// ---------------------------------------------------------------------------

/**
 * Syncs active decisions and top learnings to Claude Code's native memory files.
 * Called from session-stop to keep native memory up-to-date.
 *
 * Safe and non-blocking: swallows all errors.
 */
export function syncToNativeMemory(projectPath: string): void {
  try {
    const memDir = getNativeMemoryDir(projectPath);

    // Ensure directory exists
    fs.mkdirSync(memDir, { recursive: true });

    syncDecisions(memDir, projectPath);
    syncLearnings(memDir, projectPath);
    updateMemoryIndex(memDir);

    logger.info(`native-memory: synced to ${memDir}`);
  } catch (err) {
    logger.error(
      `native-memory: sync failed: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

function syncDecisions(memDir: string, projectPath: string): void {
  const decisions = getActiveDecisions(projectPath, 50);

  if (decisions.length === 0) {
    // Remove stale file if no decisions
    const filePath = path.join(memDir, 'decisions.md');
    try {
      fs.unlinkSync(filePath);
    } catch {
      // doesn't exist, fine
    }
    return;
  }

  const lines: string[] = [
    '# Active Decisions',
    '',
    '<!-- Auto-generated by autoclaude. Do not edit manually. -->',
    '',
  ];

  for (const d of decisions) {
    const cat = d.category ? `[${d.category}]` : '[general]';
    lines.push(`- ${cat} ${d.decision}`);
    if (d.rationale) {
      lines.push(`  - Rationale: ${d.rationale}`);
    }
  }

  lines.push('');
  fs.writeFileSync(path.join(memDir, 'decisions.md'), lines.join('\n'));
}

function syncLearnings(memDir: string, projectPath: string): void {
  const learnings = getTopLearnings(projectPath, 20);

  if (learnings.length === 0) {
    const filePath = path.join(memDir, 'learnings.md');
    try {
      fs.unlinkSync(filePath);
    } catch {
      // doesn't exist, fine
    }
    return;
  }

  const lines: string[] = [
    '# Learnings',
    '',
    '<!-- Auto-generated by autoclaude. Do not edit manually. -->',
    '',
  ];

  for (const l of learnings) {
    const cat = l.category ? `[${l.category}]` : '[general]';
    const score = l.relevance_score.toFixed(2);
    const refs =
      l.times_referenced > 0 ? ` (referenced ${l.times_referenced}x)` : '';
    lines.push(`- ${cat} ${l.learning} — relevance: ${score}${refs}`);
  }

  lines.push('');
  fs.writeFileSync(path.join(memDir, 'learnings.md'), lines.join('\n'));
}

function updateMemoryIndex(memDir: string): void {
  const indexPath = path.join(memDir, 'MEMORY.md');
  const marker = '<!-- autoclaude-sync -->';
  const section = [
    marker,
    '## AutoClaude Structured Memory',
    '',
    'See `decisions.md` for active architectural decisions with categories.',
    'See `learnings.md` for learnings ranked by relevance (with decay scores).',
    marker,
  ].join('\n');

  let content = '';
  try {
    content = fs.readFileSync(indexPath, 'utf-8');
  } catch {
    // File doesn't exist yet
  }

  // Replace existing section or append
  const startIdx = content.indexOf(marker);
  if (startIdx !== -1) {
    const endIdx = content.indexOf(marker, startIdx + marker.length);
    if (endIdx !== -1) {
      content =
        content.slice(0, startIdx) +
        section +
        content.slice(endIdx + marker.length);
    } else {
      content = content.slice(0, startIdx) + section;
    }
  } else {
    // Append to end
    content = content.trimEnd() + '\n\n' + section + '\n';
  }

  fs.writeFileSync(indexPath, content);
}
