#!/bin/bash
# Cleanup script: Remove all claude-mem artifacts
# Run this after restarting Claude Code (so claude-mem hooks are no longer active)

set -e

echo "=== Removing claude-mem plugin cache ==="
rm -rf ~/.claude/plugins/cache/thedotmack/claude-mem
echo "  Removed ~/.claude/plugins/cache/thedotmack/claude-mem"

echo ""
echo "=== Removing rust-analyzer-lsp plugin cache ==="
rm -rf ~/.claude/plugins/cache/claude-plugins-official/rust-analyzer-lsp
echo "  Removed ~/.claude/plugins/cache/claude-plugins-official/rust-analyzer-lsp"

echo ""
echo "=== Removing pure-artifact CLAUDE.md files from autoclaude ==="
cd /home/blaine/projects/autoclaude

# These files contain ONLY claude-mem-context blocks (no real content)
ARTIFACT_FILES=(
  src/cli/CLAUDE.md
  src/core/CLAUDE.md
  src/mcp/CLAUDE.md
  src/util/CLAUDE.md
  hooks/CLAUDE.md
  .claude-plugin/CLAUDE.md
  tests/CLAUDE.md
  sql/CLAUDE.md
  .github/workflows/CLAUDE.md
  dist/cli/CLAUDE.md
  dist/mcp/CLAUDE.md
)

for f in "${ARTIFACT_FILES[@]}"; do
  if [ -f "$f" ]; then
    rm "$f"
    echo "  Deleted $f"
  fi
done

echo ""
echo "=== Stripping claude-mem blocks from CLAUDE.md files with real content ==="

# autoclaude/CLAUDE.md and autoclaude/.claude/CLAUDE.md have real content
# Remove <claude-mem-context>...</claude-mem-context> blocks (including trailing newline)
for f in CLAUDE.md .claude/CLAUDE.md; do
  if [ -f "$f" ] && grep -q 'claude-mem-context' "$f"; then
    # Use perl to strip the block (handles multiline)
    perl -0777 -i -pe 's/\n*<claude-mem-context>.*?<\/claude-mem-context>\n*//gs' "$f"
    echo "  Cleaned $f"
  fi
done

echo ""
echo "=== Removing parent projects/CLAUDE.md if it's a pure artifact ==="
PARENT="/home/blaine/projects/CLAUDE.md"
if [ -f "$PARENT" ] && ! grep -v 'claude-mem-context\|Recent Activity\|auto-generated by claude-mem\|^#\|^|\|^$\|^<!--\|^---' "$PARENT" | grep -q '[a-zA-Z]'; then
  rm "$PARENT"
  echo "  Deleted $PARENT"
fi

echo ""
echo "=== Removing astro-match artifact ==="
ASTRO="/home/blaine/projects/astro-match/packages/api/src/__tests__/CLAUDE.md"
if [ -f "$ASTRO" ]; then
  rm "$ASTRO"
  echo "  Deleted $ASTRO"
fi

echo ""
echo "=== Done ==="
echo "Both plugins removed from installed_plugins.json (already done)."
echo "All claude-mem CLAUDE.md artifacts cleaned."
echo "Restart Claude Code to confirm clean state."
